# Generated by Django 5.0.14 on 2026-08-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_creditplan_user_credits_balance_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditplan',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='For non-lifetime plans: how many days until credits expire.', null=True),
        ),
        migrations.AddField(
            model_name='creditplan',
            name='plan_type',
            field=models.CharField(choices=[('lifetime', 'Lifetime'), ('one_time', 'One Time'), ('subscription', 'Subscription')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration date for purchased credits; null means never expires.', null=True),
        ),
    ]
