# Generated by Django 5.0.14 on 2026-07-11 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation_type', models.CharField(choices=[('initial', 'Initial'), ('age_stage', 'Age Stage'), ('timeline', 'Timeline'), ('age_change', 'Age Change'), ('outfit_change', 'Outfit Change'), ('high_res', 'High Res')], max_length=20)),
                ('father_photo', models.ImageField(blank=True, null=True, upload_to='inputs/fathers/')),
                ('mother_photo', models.ImageField(blank=True, null=True, upload_to='inputs/mothers/')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age_stage', models.CharField(blank=True, max_length=20, null=True)),
                ('background', models.CharField(blank=True, max_length=20, null=True)),
                ('outfit', models.CharField(blank=True, max_length=50, null=True)),
                ('timeline', models.CharField(blank=True, max_length=20, null=True)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='generated/')),
                ('high_res_image', models.ImageField(blank=True, null=True, upload_to='generated/highres/')),
                ('eyes_similarity', models.FloatField(blank=True, null=True)),
                ('face_shape_similarity', models.FloatField(blank=True, null=True)),
                ('skin_tone_similarity', models.FloatField(blank=True, null=True)),
                ('ai_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('external_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='babies.babyimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_favorite'], name='babies_baby_user_id_408b86_idx'), models.Index(fields=['user', 'is_deleted'], name='babies_baby_user_id_a92684_idx')],
            },
        ),
    ]
