# Generated by Django 5.0.14 on 2026-08-15 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Main prompt text. Use placeholders like {gender}, {age_stage}, {background}, {outfit}.')),
                ('negative_prompt', models.TextField(blank=True)),
                ('variables', models.TextField(blank=True, help_text='Comma-separated variable names supported by this prompt.')),
                ('category', models.CharField(choices=[('General Prompt', 'General Prompt'), ('Background Prompt', 'Background Prompt'), ('Theme Prompt', 'Theme Prompt'), ('Monthly Prompt', 'Monthly Prompt'), ('Holiday Prompt', 'Holiday Prompt'), ('Birthday Prompt', 'Birthday Prompt'), ('System Prompt', 'System Prompt'), ('Safety Prompt', 'Safety Prompt'), ('Negative Prompt', 'Negative Prompt')], default='General Prompt', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='Portrait', max_length=50)),
                ('background', models.ImageField(blank=True, null=True, upload_to='templates/backgrounds/')),
                ('theme', models.CharField(blank=True, max_length=50)),
                ('background_type', models.CharField(blank=True, max_length=50)),
                ('ai_prompt', models.TextField(help_text='Template-specific prompt text combined with the active GenerationPrompt during generation.')),
                ('maintain_face_identity', models.BooleanField(default=True)),
                ('keep_original_gender', models.BooleanField(default=True)),
                ('keep_original_age', models.BooleanField(default=True)),
                ('enhance_lighting', models.BooleanField(default=False)),
                ('high_quality_rendering', models.BooleanField(default=True)),
                ('allow_background_blur', models.BooleanField(default=True)),
                ('prompt_weight', models.FloatField(default=1.0)),
                ('negative_prompt', models.TextField(blank=True)),
                ('seed', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='babyimage',
            name='generation_prompt_text',
            field=models.TextField(blank=True, help_text='Final assembled prompt used for generation.'),
        ),
        migrations.AddField(
            model_name='babyimage',
            name='generation_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baby_images', to='babies.generationprompt'),
        ),
        migrations.AddField(
            model_name='babyimage',
            name='generation_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baby_images', to='babies.generationtemplate'),
        ),
        migrations.CreateModel(
            name='ParentPhotoScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('father_photo', models.ImageField(upload_to='scans/fathers/')),
                ('mother_photo', models.ImageField(upload_to='scans/mothers/')),
                ('father_scan_status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('mother_scan_status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('father_scan_details', models.JSONField(blank=True, default=dict)),
                ('mother_scan_details', models.JSONField(blank=True, default=dict)),
                ('overall_status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('scan_result', models.CharField(choices=[('Clean', 'Clean'), ('No Face Detected', 'No Face Detected'), ('Duplicate', 'Duplicate'), ('NSFW Detected', 'NSFW Detected'), ('Watermark Detected', 'Watermark Detected'), ('Pending Analysis', 'Pending Analysis'), ('Scanning...', 'Scanning...')], default='Pending Analysis', max_length=30)),
                ('confidence', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('moderator_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_photo_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='babyimage',
            name='parent_photo_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baby_images', to='babies.parentphotoscan'),
        ),
    ]
