# Generated by Django 5.0.14 on 2026-08-15 06:53

from django.db import migrations


def create_defaults(apps, schema_editor):
    GenerationPrompt = apps.get_model('babies', 'GenerationPrompt')
    GenerationTemplate = apps.get_model('babies', 'GenerationTemplate')

    if not GenerationPrompt.objects.filter(status='active').exists():
        GenerationPrompt.objects.create(
            title='Default Baby Portrait Prompt',
            description='Base prompt used when no other active prompt exists.',
            content='Generate a realistic, high-quality portrait of a baby using the uploaded parent photos. Maintain natural facial identity, soft lighting, and lifelike skin tones.',
            negative_prompt='distorted face, unnatural proportions, blurry, low quality, deformed',
            variables='gender, age_stage, background, outfit',
            category='General Prompt',
            status='active',
        )

    if not GenerationTemplate.objects.filter(status='active').exists():
        GenerationTemplate.objects.create(
            name='Default Studio Template',
            description='Default soft studio background template.',
            category='Portrait',
            theme='Studio',
            background_type='Studio',
            ai_prompt='Place the baby in a soft studio setting with gentle, diffused lighting and a clean background.',
            maintain_face_identity=True,
            keep_original_gender=True,
            keep_original_age=True,
            enhance_lighting=True,
            high_quality_rendering=True,
            allow_background_blur=False,
            prompt_weight=1.0,
            status='active',
        )


def remove_defaults(apps, schema_editor):
    GenerationPrompt = apps.get_model('babies', 'GenerationPrompt')
    GenerationTemplate = apps.get_model('babies', 'GenerationTemplate')
    GenerationPrompt.objects.filter(title='Default Baby Portrait Prompt').delete()
    GenerationTemplate.objects.filter(name='Default Studio Template').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0002_generationprompt_generationtemplate_and_more'),
    ]

    operations = [
        migrations.RunPython(create_defaults, remove_defaults),
    ]
