# Generated by Django 5.0.14 on 2026-08-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0003_auto_20260815_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_ai_scanning', models.BooleanField(default=True)),
                ('enable_face_detection', models.BooleanField(default=True)),
                ('enable_nsfw_detection', models.BooleanField(default=False)),
                ('enable_duplicate_detection', models.BooleanField(default=True)),
                ('enable_watermark_detection', models.BooleanField(default=False)),
                ('enable_identity_matching', models.BooleanField(default=False)),
                ('minimum_confidence', models.FloatField(default=0.75)),
                ('auto_reject', models.BooleanField(default=False)),
                ('manual_review', models.BooleanField(default=True)),
                ('max_upload_size', models.PositiveIntegerField(default=10)),
                ('allowed_image_types', models.CharField(default='png, jpg, webp', max_length=255)),
                ('blocked_words', models.TextField(default='violence, gore, explicit, hate, weapons')),
                ('blocked_prompt_list', models.TextField(default='nude, naked, sexual, gore, violent')),
                ('negative_prompt_settings', models.TextField(default='low quality, blurry, distorted, deformed, bad anatomy')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Safety Settings',
            },
        ),
    ]
