# Generated by Django 6.0.8 on 2026-08-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0004_safetysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyimage',
            name='ai_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
