# Generated by Django 6.0.8 on 2026-08-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0005_alter_babyimage_ai_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyimage',
            name='request_context',
            field=models.JSONField(blank=True, help_text='Snapshot of the exact request config + resolved prompt segments used for this image.', null=True),
        ),
    ]
